apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hello
  name: hello
spec:
  type: LoadBalancer
  ports:
    - name: "6060"
      port: 6060
      targetPort: 8080
  selector:
    io.kompose.service: hello
status:
  loadBalancer: {}
