version: "3"
services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "A_P@ssw0rd"
      ACCEPT_EULA: "Y"
  dremio:
    container_name: dremio
    image: dremio/dremio-oss
    volumes:
    - .:/data/dremio
    ports:
    - "9047:9047"
    - "31010:31010"
    - "32010:32010"
    - "45678:45678"
    links:
      - mssql