apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: spark
  name: spark
spec:
  type: LoadBalancer
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8080
  selector:
    io.kompose.service: spark
status:
  loadBalancer: {}
