apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.7.0
    component: create-user-job
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-create-user-job
  namespace: default

