apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    chart: airflow-1.7.0
    component: redis
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-redis
  namespace: default
spec:
  selector:
    matchLabels:
      component: redis
      release: airflow
      tier: airflow
  serviceName: airflow-redis
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        component: redis
        release: airflow
        tier: airflow
    spec:
      affinity: {}
      containers:
      - args:
        - -c
        - redis-server --requirepass ${REDIS_PASSWORD}
        command:
        - /bin/sh
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: airflow-redis-password
        image: redis:6-bullseye
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis-db
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-db
      nodeSelector: {}
      securityContext:
        runAsUser: 0
      serviceAccountName: airflow-redis
      tolerations: []
      topologySpreadConstraints: []
  volumeClaimTemplates:
  - metadata:
      name: redis-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

