apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    chart: airflow-1.7.0
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-pod-log-reader-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list

