apiVersion: v1
kind: Service
metadata:
  labels:
    chart: airflow-1.7.0
    component: worker
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-worker
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: worker-logs
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    component: worker
    release: airflow
    tier: airflow

