apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.5.3
  name: airflow-postgresql
  namespace: default
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/name: postgresql
    role: primary
  type: ClusterIP

