apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    chart: airflow-1.7.0
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-pod-log-reader-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-log-reader-role
subjects:
- kind: ServiceAccount
  name: airflow-webserver
  namespace: default
- kind: ServiceAccount
  name: airflow-triggerer
  namespace: default

