apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nessie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nessie
    app.kubernetes.io/version: 0.46.2
    helm.sh/chart: nessie-0.46.2
  name: nessie
spec:
  ports:
  - name: nessie-server
    port: 19120
    protocol: TCP
    targetPort: 19120
  selector:
    app.kubernetes.io/instance: nessie
    app.kubernetes.io/name: nessie
  type: LoadBalancer

