apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nessie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nessie
    app.kubernetes.io/version: 0.46.2
    helm.sh/chart: nessie-0.46.2
  name: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nessie
      app.kubernetes.io/name: nessie
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nessie
        app.kubernetes.io/name: nessie
    spec:
      containers:
      - env:
        - name: NESSIE_VERSION_STORE_TYPE
          value: INMEMORY
        - name: QUARKUS_LOG_LEVEL
          value: INFO
        - name: QUARKUS_CONSOLE_LOG_LEVEL
          value: INFO
        - name: QUARKUS_LOG_FILE_LEVEL
          value: INFO
        image: projectnessie/nessie:0.46.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 19120
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: nessie
        ports:
        - containerPort: 19120
          name: nessie-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 19120
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 45
          successThreshold: 1
          timeoutSeconds: 10
        resources: 
          limits:
            cpu: 50m
            memory: 100Mi
        securityContext: {}
      securityContext: {}
      serviceAccountName: nessie

