apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterRole.yaml  
  - config-map.yaml  
  - prometheus-deployment.yaml  
  - prometheus-ingress.yaml  
  - prometheus-service.yaml