apiVersion: v1
kind: Service
metadata:
  labels:
    chart: airflow-1.7.0
    component: redis
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-redis
  namespace: default
spec:
  ports:
  - name: redis-db
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    component: redis
    release: airflow
    tier: airflow
  type: ClusterIP

