apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.7.0
    component: webserver
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-webserver
  namespace: default

