apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: airflow-1.7.0
    component: statsd
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-statsd
  namespace: default

