apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    chart: airflow-1.7.0
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-pod-launcher-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - list
  - get
  - patch
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list

