apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - airflow-worker-deployment.yaml
  - airflow-worker-claim0-persistentvolumeclaim.yaml
  - airflow-worker-claim1-persistentvolumeclaim.yaml
  - airflow-worker-claim2-persistentvolumeclaim.yaml