apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dremio
  name: dremio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dremio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: dremio
    spec:
      containers:
        - image: dremio/dremio-oss
          name: dremio
          ports:
            - containerPort: 9047
            - containerPort: 31010
            - containerPort: 32010
            - containerPort: 45678
          resources: 
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - mountPath: /data/dremio
              name: dremio-claim0
      restartPolicy: Always
      volumes:
        - name: dremio-claim0
          persistentVolumeClaim:
            claimName: dremio-claim0
status: {}
